### PR TITLE
Fix #36 -- switch to graphviz 0.18

### LINKED ISSUE #36: Graphviz 0.18 incompatibility
There was a recent Graphviz release, which seem to break this package.

https://github.com/xflr6/graphviz/blob/master/CHANGES.rst#version-018

After a quick check, I see at least one issue:
https://github.com/xflr6/graphviz/commit/17df6131746d3549eea08c6a7f5934698cf23f8a changed behaviour of private `_head` and `_head_strict` attributes - they are static methods now.

I am happy to help, but not familiar with the codebase.
Nevertheless, I guess they way to go would be:
1. Pin graphviz to `<0.18` and release a minor/bugfix version
2. Fix incompatibility and release a new major version

What do you think?

### PR DESCRIPTION
**Pull request by amureki**
- Use static methods instead of "%" operator. This reflects xflr6/graphviz@17df613
- Use quoting instead of lang. Reflects xflr6/graphviz@673261d
- Use new `encoding` argument instead of manual decoding https://github.com/xflr6/graphviz/blob/master/CHANGES.rst#version-018
- Adjust tests to handle newlines https://github.com/xflr6/graphviz/blob/master/CHANGES.rst#version-018
- Pin graphwiz>=0.18

### CODE REVIEW

**Comment by amureki** [comment]
@codingjoe could you, please, approve the workflow?

**Review by codingjoe — APPROVED** [review]
LGTM, thanks @amureki

**Comment by codingjoe** [comment]
@amureki, the CI pipeline is broken because of the new psycopg release. Maybe you could add a commit for that too.

**Comment by amureki** [comment]
> @amureki, the CI pipeline is broken because of the new psycopg release. Maybe you could add a commit for that too.

It actually failed due to a test I missed (did not run locally without a celery worker). Now it is fixed.
Not sure if I am tracing anything related to psycopg. I think it is okay here, but if I am missing anything, please, give me a hint. :)

**Comment by amureki** [comment]
Also, should this go as 1.1.0, or it is okay under 1.0.6?

**Comment by codingjoe** [comment]
1.0.6, since this is bugfix, right?

**Pull request merged**
